{
  "contest": 304,
  "handle": "attacklancer",
  "risk": "2",
  "title": " Reentrancy in function withdraw",
  "issueId": 59,
  "issueUrl": "https://github.com/code-423n4/2023-11-zetachain-findings/issues/59"
}